app = "koi-express"       # Tên ứng dụng trên Fly.io
primary_region = "sin"      # Vùng triển khai chính (có thể thay đổi theo yêu cầu)

[env]
SPRING_PROFILES_ACTIVE = "prod"  # Kích hoạt cấu hình production cho Spring Boot

[[services]]
internal_port = 8080        # Cổng nội bộ mà ứng dụng chạy (phù hợp với EXPOSE trong Dockerfile)
protocol = "tcp"            # Giao thức TCP

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
port = 80                 # Cổng bên ngoài
handlers = ["http"]       # Xử lý HTTP

[[services.http_checks]]
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "get"
path = "/actuator/health" # Đường dẫn health check của Spring Boot actuator
protocol = "http"
port = 80
