spring:
  application:
    name: Koi-Express

  datasource:
    url: jdbc:mysql://localhost:3306/koi_express
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

    main:
      allow-circular-references: true

jwt:
  secret-key: "Qcm41hV7dw/EE0Eo8oY87pkREbUoZaU78LZZCbsCq9iqCBWmFUqsLVHVA36CGOEr"





spring.config.import: "classpath:application-secret.yaml"

