spring:
  datasource:
    username: root
    password: 12345

  mail:
    username: kn5253689@gmail.com
    password: umzj lrkl nxdh bdly

  security:
    user:
      name: user
      password: password

    oauth2:
      client:
        registration:
          google:
            client-id: "230790509660-s304ceefoirbiltr80mscfloqfjq2kl5.apps.googleusercontent.com"
            client-secret: "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"
          facebook:
            client-id: "1216046793001793"
            client-secret: "a7df9a9d988432151aa19fe1e7e19d64"

jwt:
  secret-key: Qcm41hV7dw/EE0Eo8oY87pkREbUoZaU78LZZCbsCq9iqCBWmFUqsLVHVA36CGOEr
