spring:
  application:
    name: Koi-Express

  datasource:
    url: jdbc:mysql://localhost:3306/koi_express
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring.config.import: "classpath:application-secret.yaml"