spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  manager:
    email: ${MANAGER_EMAIL:manager@koi-express.com}
    password: ${MANAGER_PASSWORD:manager123}

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  security:
    user:
      name: user
      password: password

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}

  twilio:
    TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN:  ${TWILIO_AUTH_TOKEN}
    TWILIO_FROM_PHONE:  ${TWILIO_FROM_PHONE}

jwt:
  secret-key: ${JWT_SECRET_KEY:default-secret-key}
