spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            client-id: 230790509660-s304ceefoirbiltr80mscfloqfjq2kl5.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          facebook:
            client-id: 230790509660-s304ceefoirbiltr80mscfloqfjq2kl5.apps.googleusercontent.com
            client-secret: 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
            scope:
              - public_profile
              - email

  datasource:
    username: root
    password: 12345

