spring:
  application:
    name: Koi-Express
  port:
    server: 8080

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/koi_express
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    main:
      allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - profile
              - email
          facebook:
            scope:
              - public_profile
              - email

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  payment:
    vnPay:
      url: ${PAY_URL}
      tmnCode: ${TMN_CODE}
      secretKey: ${SECRET_KEY}
      returnUrl: ${RETURN_URL}
      version: ${VERSION}
      command: ${COMMAND}
      orderType: ${ORDER_TYPE}

  config:
    import: application-secret.yaml

  logging:
    level:
      root: INFO
      com.koi_express: DEBUG

  sever:
    servlet:
      session:
        timeout: 30m


