spring:
  datasource:
    username: root
    password: 12345

  mail:
    username: kn5253689@gmail.com
    password: umzj lrkl nxdh bdly
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  security:
    user:
      name: user
      password: password

    oauth2:
      client:
        registration:
          google:
            client-id: "230790509660s304ceefoirbiltr80mscfloqfjq2kl5.apps.googleusercontent.com"
            client-secret: "GOCSPXZGobDwPmKlhZdZCWA4Yt5GebprHu"
          facebook:
            client-id: "1216046793001793"
            client-secret: "a7df9a9d988432151aa19fe1e7e19d64"

  twilio:
    TWILIO_ACCOUNT_SID: "AC6ebe5c4cf2fb07c85783a6dbee771aae"
    TWILIO_AUTH_TOKEN:  "bcaba2ac146c3b645c212aa82d5f96f7"
    TWILIO_FROM_PHONE:  "+13182521661"

jwt:
    secret-key: "Qcm41hV7dw/EE0Eo8oY87pkREbUoZaU78LZZCbsCq9iqCBWmFUqsLVHVA36CGOEr"

