version: '3.8'

services:
  mysql-db:
    container_name: some-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: koi_express
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - koi-express-net

  koi-express-app:
    container_name: koi-express-container
    image: koi-express:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://some-mysql:3306/koi_express
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql-db
    networks:
      - koi-express-net

networks:
  koi-express-net:
    driver: bridge
