version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fpt
      MYSQL_DATABASE: koi-express
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_HOST:  192.168.1.2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
