version: '3.8'

services:
  mysql-db:
    container_name: some-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: koi_express
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - koi-express-net

networks:
  koi-express-net:
    driver: bridge
